### ISSUE TITLE
Add the possibility to change the read timeout for the httpclient

### ISSUE THREAD

**Issue by antoinedvd** [senx/warp10-ext-influxdb#2]
It could be usefull to have the possibility to change the default **read timeout** value used by `InfluxDBFactory` (OkHttpClient).
We can take this opportunity to do the same for the **write timeout**.

To do this I propose to add 2 new parameters in the entry map (see the 2 last in this array) : 
| Key | Description |
|-----|-------------|
| `url` | URL of the InfluxDB endpoint to use. |
| `db` | Name of the InfluxDB database to access. |
| `user` | User used for authentification. |
| `password` | Password associated with `user`. |
| `influxql` | [InfluxQL](https://docs.influxdata.com/influxdb/v1.8/query_language/) queries, separated by semi-colons. Queries should contain a GROUP BY clause otherwise tags will be interpreted as fields and produce GTS of their own. |
| `readTimeout` | The timeout used to execute read query (which is a value define from this [link](https://square.github.io/okhttp/4.x/okhttp/okhttp3/-ok-http-client/-builder/read-timeout/))
| `writeTimeout` | The timeout used to execute write query (which is a value define from this [link](https://square.github.io/okhttp/4.x/okhttp/okhttp3/-ok-http-client/-builder/write-timeout)

**Comment by hbs** [comment]
Fixed by #3
